import Head from 'next/head'
import Sidenav from '@/components/Sidenav'
import SearchBar from '@/components/SearchBar'
import CategoryList from '@/components/CategoryList'
import Nearby from '@/components/Nearby'
import GlobalApi from '@/util/GlobalApi'
import { useContext, useEffect, useState } from 'react'
import { UserLocationContext } from '@/context/UserLocationContext'
import Map from '@/components/Map'
import { SelectedBusinessContext } from '@/context/SelectedBusinessContext'
import Jump from '@/components/Jump'


export default function Home() {
  const [nearbyPlacesList, setNearbyPlacesList] = useState([]);
  const { userLocation, setUserLocation } = useContext(UserLocationContext);
  const [selectedNearbyPlace, setSelectedNearbyPlace] = useState([]);

  useEffect(() => {
    if (userLocation) {
      getNearbyPlace('restaurant');
    }
    console.log(userLocation);
  }, [userLocation])
  const getNearbyPlace = (category) => {
    // GlobalApi.getNearByPlace('restaurant','18.922064','72.834641')
    // GlobalApi.getNearByPlace(category,'29.951065','-90.071533')
    GlobalApi.getNearByPlace(category, userLocation?.lat, userLocation?.lng)
      .then(resp => {
        // console.log(resp.data.results);
        setNearbyPlacesList(resp.data.results)
      })
  }
  return (
    <div className='flex '>
      <SelectedBusinessContext.Provider value={{selectedNearbyPlace,setSelectedNearbyPlace}}>
        <Head>
          <title>AasPaas Web App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <Sidenav />
        <div className='grid grid-cols-1 md:grid-cols-2 px-6 md:px-10 w-full gap-8 mt-10'>
          <div>
            <SearchBar nearbyPlacesList={nearbyPlacesList} setNearbyPlacesList={setNearbyPlacesList} />
            <CategoryList setSelectedCategory={((category) => getNearbyPlace(category))} />
            <Nearby nearbyPlacesList={nearbyPlacesList} />
          </div>

          <div className='sm:order-first md:order-last'>
            <Map nearbyPlacesList={nearbyPlacesList} />
            <Jump/>
          </div>
        </div>
      </SelectedBusinessContext.Provider>

    </div >
  )
}
